package com.tanidikvar.api.verification.controller;
import com.tanidikvar.api.auth.security.SessionPrincipal;import com.tanidikvar.api.common.dto.*;import com.tanidikvar.api.common.error.DomainException;import com.tanidikvar.api.verification.dto.*;import com.tanidikvar.api.verification.repository.EducationVerificationRepository;import com.tanidikvar.api.verification.service.EducationVerificationService;import jakarta.validation.Valid;import java.util.UUID;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api")public class EducationVerificationController{private final EducationVerificationService service;private final EducationVerificationRepository repository;public EducationVerificationController(EducationVerificationService service,EducationVerificationRepository repository){this.service=service;this.repository=repository;}
 @GetMapping("/me/education-verification")public EducationVerificationResponse get(@AuthenticationPrincipal SessionPrincipal user){return service.get(user.userId());}
 @PostMapping("/me/education-verification/school-email")@ResponseStatus(HttpStatus.ACCEPTED)public void request(@AuthenticationPrincipal SessionPrincipal user,@Valid@RequestBody SchoolEmailRequest request){service.request(user.userId(),request);}
 @PostMapping("/me/education-verification/school-email/confirm")public EducationVerificationResponse confirm(@AuthenticationPrincipal SessionPrincipal user,@Valid@RequestBody SchoolEmailConfirmRequest request){return service.confirm(user.userId(),request);}
 @PostMapping("/me/education-verification/graduate-review")@ResponseStatus(HttpStatus.ACCEPTED)public void graduate(@AuthenticationPrincipal SessionPrincipal user,@Valid@RequestBody GraduateVerificationRequest request){service.graduate(user.userId(),request);}
 @GetMapping("/manager/education-verifications")@PreAuthorize("hasRole('MANAGER')")public PageResponse<GraduateReviewResponse> reviews(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){SearchQuery.page(page,size);return new PageResponse<>(repository.reviews(page,size),page,size,repository.reviewCount());}
 @PutMapping("/manager/education-verifications/{id}")@PreAuthorize("hasRole('MANAGER')")public GraduateReviewResponse decide(@AuthenticationPrincipal SessionPrincipal user,@PathVariable UUID id,@Valid@RequestBody GraduateDecisionRequest request){if(!repository.decide(id,user.userId(),request))throw new DomainException(409,"STALE_VERSION","Başvuru daha önce değişmiş.");return repository.review(id);}}
