package com.tanidikvar.api.decision.repository;
import com.tanidikvar.api.decision.dto.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;
@Repository public class DecisionContributionRepository{
 private final JdbcTemplate jdbc;public DecisionContributionRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public boolean university(UUID id){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM universities WHERE id=? AND deleted_at IS NULL)",Boolean.class,id));}
 private boolean normalized(UUID university,UUID program){return program!=null&&Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM programs WHERE id=? AND university_id=? AND deleted_at IS NULL)",Boolean.class,program,university));}
 public boolean program(UUID university,UUID program){return normalized(university,program)||Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM university_departments WHERE id=? AND university_id=? AND deleted_at IS NULL)",Boolean.class,program,university));}
 public boolean verified(UUID user){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM education_verifications WHERE user_id=? AND verified_at IS NOT NULL AND deleted_at IS NULL)",Boolean.class,user));}
 public void metric(UUID user,MetricContributionRequest r){if(r.programId()==null||!normalized(r.universityId(),r.programId())){jdbc.update("INSERT INTO context_metrics(id,user_id,university_id,university_department_id,metric_key,numeric_value,verified) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id,university_id,university_department_id,metric_key) DO UPDATE SET numeric_value=excluded.numeric_value,verified=excluded.verified,deleted_at=NULL,updated_at=CURRENT_TIMESTAMP,version=context_metrics.version+1",UUID.randomUUID(),user,r.universityId(),r.programId(),r.metricKey(),r.value(),verified(user));}else jdbc.update("INSERT INTO context_metrics(id,user_id,university_id,program_id,metric_key,numeric_value,verified) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id,university_id,program_id,metric_key) WHERE program_id IS NOT NULL DO UPDATE SET numeric_value=excluded.numeric_value,verified=excluded.verified,deleted_at=NULL,updated_at=CURRENT_TIMESTAMP,version=context_metrics.version+1",UUID.randomUUID(),user,r.universityId(),r.programId(),r.metricKey(),r.value(),verified(user));}
 public List<MetricSummaryResponse> metrics(UUID university,UUID program){String column=normalized(university,program)?"program_id":"university_department_id";return jdbc.query("SELECT metric_key,round(avg(numeric_value),2) average,count(*) samples,count(*) FILTER(WHERE verified) verified_samples,max(updated_at) updated_at FROM context_metrics WHERE university_id=? AND "+column+" IS NOT DISTINCT FROM ? AND deleted_at IS NULL GROUP BY metric_key ORDER BY metric_key",(r,n)->{long count=r.getLong("samples");boolean sensitive=Set.of("MONTHLY_HOUSING_COST","MONTHLY_TRANSPORT_COST","MONTHLY_FOOD_COST","JOB_SEARCH_MONTHS").contains(r.getString("metric_key")),visible=!sensitive||count>=5;return new MetricSummaryResponse(r.getString("metric_key"),visible?r.getBigDecimal("average"):null,count,r.getLong("verified_samples"),r.getTimestamp("updated_at").toInstant(),visible);},university,program);}
 public ExperienceResponse experience(UUID user,ExperienceRequest r,String sentiment){UUID id=UUID.randomUUID();String column=normalized(r.universityId(),r.programId())?"program_id":"university_department_id";return jdbc.query("INSERT INTO structured_experiences(id,author_id,university_id,"+column+",template_type,title,body,sentiment) VALUES (?,?,?,?,?,?,?,?) RETURNING id,template_type,title,body,sentiment,created_at,version",(row,n)->new ExperienceResponse(row.getObject("id",UUID.class),user,name(user),row.getString("template_type"),row.getString("title"),row.getString("body"),row.getString("sentiment"),row.getTimestamp("created_at").toInstant(),row.getLong("version")),id,user,r.universityId(),r.programId(),r.templateType(),r.title().trim(),r.body().trim(),sentiment).getFirst();}
 public List<ExperienceResponse> experiences(UUID university,UUID program,int page,int size){String column=normalized(university,program)?"program_id":"university_department_id";return jdbc.query("SELECT se.*,concat(up.first_name,' ',up.last_name) author_name FROM structured_experiences se JOIN user_profiles up ON up.user_id=se.author_id WHERE se.university_id=? AND se."+column+" IS NOT DISTINCT FROM ? AND se.deleted_at IS NULL ORDER BY se.created_at DESC,se.id LIMIT ? OFFSET ?",(r,n)->new ExperienceResponse(r.getObject("id",UUID.class),r.getObject("author_id",UUID.class),r.getString("author_name"),r.getString("template_type"),r.getString("title"),r.getString("body"),r.getString("sentiment"),r.getTimestamp("created_at").toInstant(),r.getLong("version")),university,program,size,page*size);}
 public long experienceCount(UUID university,UUID program){String column=normalized(university,program)?"program_id":"university_department_id";return jdbc.queryForObject("SELECT count(*) FROM structured_experiences WHERE university_id=? AND "+column+" IS NOT DISTINCT FROM ? AND deleted_at IS NULL",Long.class,university,program);}
 private String name(UUID user){return jdbc.queryForObject("SELECT concat(first_name,' ',last_name) FROM user_profiles WHERE user_id=? AND deleted_at IS NULL",String.class,user);}
 public boolean graduate(UUID user){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM user_profiles WHERE user_id=? AND education_status='MEZUN' AND deleted_at IS NULL)",Boolean.class,user));}
 public void career(UUID user,GraduateOutcomeRequest r){if(normalized(r.universityId(),r.programId()))jdbc.update("INSERT INTO graduate_outcomes(id,user_id,university_id,program_id,sector,first_role,company_type,graduate_study,job_search_months,verified) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,program_id) WHERE program_id IS NOT NULL DO UPDATE SET sector=excluded.sector,first_role=excluded.first_role,company_type=excluded.company_type,graduate_study=excluded.graduate_study,job_search_months=excluded.job_search_months,verified=excluded.verified,deleted_at=NULL,updated_at=CURRENT_TIMESTAMP,version=graduate_outcomes.version+1",UUID.randomUUID(),user,r.universityId(),r.programId(),r.sector().trim(),r.firstRole().trim(),r.companyType().trim(),r.graduateStudy(),r.jobSearchMonths(),verified(user));else jdbc.update("INSERT INTO graduate_outcomes(id,user_id,university_id,university_department_id,sector,first_role,company_type,graduate_study,job_search_months,verified) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,university_department_id) DO UPDATE SET sector=excluded.sector,first_role=excluded.first_role,company_type=excluded.company_type,graduate_study=excluded.graduate_study,job_search_months=excluded.job_search_months,verified=excluded.verified,deleted_at=NULL,updated_at=CURRENT_TIMESTAMP,version=graduate_outcomes.version+1",UUID.randomUUID(),user,r.universityId(),r.programId(),r.sector().trim(),r.firstRole().trim(),r.companyType().trim(),r.graduateStudy(),r.jobSearchMonths(),verified(user));}
 private List<CareerCategoryResponse> categories(String category,UUID university,UUID program){String safe=switch(category){case"sector"->"sector";case"first_role"->"first_role";case"company_type"->"company_type";default->throw new IllegalArgumentException("category");},identity=normalized(university,program)?"program_id":"university_department_id";return jdbc.query("SELECT "+safe+" label,count(*) amount FROM graduate_outcomes WHERE university_id=? AND "+identity+"=? AND deleted_at IS NULL GROUP BY "+safe+" ORDER BY amount DESC,label LIMIT 8",(r,n)->new CareerCategoryResponse(r.getString("label"),r.getLong("amount")),university,program);}
 public CareerSummaryResponse careerSummary(UUID university,UUID program){String column=normalized(university,program)?"program_id":"university_department_id";return jdbc.queryForObject("SELECT count(*) samples,count(*) FILTER(WHERE verified) verified_samples,round(avg(job_search_months),1) average_months,count(*) FILTER(WHERE graduate_study) graduate_study,max(updated_at) updated_at FROM graduate_outcomes WHERE university_id=? AND "+column+"=? AND deleted_at IS NULL",(r,n)->{long count=r.getLong("samples"),verified=r.getLong("verified_samples");boolean visible=count>=5;return new CareerSummaryResponse(count,verified,visible?r.getBigDecimal("average_months"):null,visible?r.getLong("graduate_study"):0,visible?categories("sector",university,program):List.of(),visible?categories("first_role",university,program):List.of(),visible?categories("company_type",university,program):List.of(),r.getTimestamp("updated_at")==null?null:r.getTimestamp("updated_at").toInstant(),visible);},university,program);}
 public SentimentSummaryResponse sentiments(UUID university,UUID program){String column=normalized(university,program)?"program_id":"university_department_id",sql="SELECT title,count(*) amount FROM structured_experiences WHERE university_id=? AND "+column+" IS NOT DISTINCT FROM ? AND sentiment=? AND deleted_at IS NULL GROUP BY title ORDER BY amount DESC,title LIMIT 3";return new SentimentSummaryResponse(jdbc.query(sql,(r,n)->new CareerCategoryResponse(r.getString("title"),r.getLong("amount")),university,program,"POSITIVE"),jdbc.query(sql,(r,n)->new CareerCategoryResponse(r.getString("title"),r.getLong("amount")),university,program,"NEGATIVE"));}
}
