package com.tanidikvar.api.report.service;
import com.tanidikvar.api.report.dto.*;import com.tanidikvar.api.report.repository.QuestionReportRepository;import com.tanidikvar.api.auth.service.AccountAccessService;import com.tanidikvar.api.auth.entity.Authority;import com.tanidikvar.api.common.dto.*;import com.tanidikvar.api.common.error.DomainException;import com.tanidikvar.api.question.service.QuestionAccessService;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class QuestionReportService{
 private final QuestionReportRepository reports;private final AccountAccessService accounts;private final QuestionAccessService questions;
 public QuestionReportService(QuestionReportRepository reports,AccountAccessService accounts,QuestionAccessService questions){this.reports=reports;this.accounts=accounts;this.questions=questions;}
 @Transactional public QuestionReportResponse create(UUID actor,UUID question,QuestionReportRequest request){accounts.lockActive(actor);questions.requireReadable(question);UUID id=UUID.randomUUID();try{reports.create(id,question,actor,request.reason().strip());}catch(org.springframework.dao.DuplicateKeyException e){throw new DomainException(409,"REPORT_EXISTS","Bu soruyu daha önce şikâyet ettin.");}return reports.find(id).orElseThrow();}
 @Transactional public ContentReportResponse createContent(UUID actor,String type,UUID target,QuestionReportRequest request){accounts.lockActive(actor);if(!reports.reportable(type,target,actor))throw new DomainException(404,"NOT_FOUND","Şikâyet edilebilir içerik bulunamadı.");try{return reports.createContent(UUID.randomUUID(),type,target,actor,request.reason().strip());}catch(org.springframework.dao.DuplicateKeyException e){throw new DomainException(409,"REPORT_EXISTS","Bu içeriği daha önce şikâyet ettin.");}}
 private void manager(UUID actor){if(accounts.lockActive(actor).getAuthority()!=Authority.MANAGER)throw new DomainException(403,"ACCESS_DENIED","Manager yetkisi gerekiyor.");}
 @Transactional public PageResponse<QuestionReportResponse> list(UUID actor,String q,String status,String sort,int page,int size){manager(actor);SearchQuery.page(page,size);if(!Set.of("","OPEN","RESOLVED","DISMISSED").contains(status)||!Set.of("NEWEST","OLDEST","STATUS").contains(sort))throw new DomainException(400,"INVALID_REQUEST","Filtreleri kontrol et.");String clean=SearchQuery.clean(q);return new PageResponse<>(reports.list(clean,status,sort,page,size),page,size,reports.count(clean,status));}
 @Transactional public QuestionReportResponse decide(UUID actor,UUID id,QuestionReportDecision request){manager(actor);var current=reports.find(id).orElseThrow(()->new DomainException(404,"NOT_FOUND","Şikâyet bulunamadı."));if(current.version()!=request.version())throw new DomainException(409,"STALE_VERSION","Şikâyet değişmiş; listeyi yenile.");reports.decide(id,actor,request.status(),request.reason().strip());return reports.find(id).orElseThrow();}
 @Transactional public PageResponse<ManagedContentReportResponse> listContent(UUID actor,String q,String status,String sort,int page,int size){manager(actor);SearchQuery.page(page,size);if(!Set.of("","OPEN","RESOLVED","DISMISSED").contains(status)||!Set.of("NEWEST","OLDEST","STATUS").contains(sort))throw new DomainException(400,"INVALID_REQUEST","Filtreleri kontrol et.");String clean=SearchQuery.clean(q);return new PageResponse<>(reports.listContent(clean,status,sort,page,size),page,size,reports.countContent(clean,status));}
 @Transactional public ManagedContentReportResponse decideContent(UUID actor,UUID id,QuestionReportDecision request){manager(actor);var current=reports.findContent(id).orElseThrow(()->new DomainException(404,"NOT_FOUND","İçerik şikâyeti bulunamadı."));if(current.version()!=request.version())throw new DomainException(409,"STALE_VERSION","Şikâyet değişmiş; listeyi yenile.");reports.decideContent(id,actor,request.status(),request.reason().strip());return reports.findContent(id).orElseThrow();}
}
