package com.tanidikvar.api.verification.repository;
import com.tanidikvar.api.verification.dto.*;import java.sql.*;import java.time.Instant;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;import org.springframework.transaction.annotation.Transactional;
@Repository public class EducationVerificationRepository{private final JdbcTemplate jdbc;public EducationVerificationRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public boolean eligible(UUID user){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM user_profiles WHERE user_id=? AND education_status='UNIVERSITE_OGRENCISI' AND deleted_at IS NULL)",Boolean.class,user));}
 public boolean graduate(UUID user){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM user_profiles WHERE user_id=? AND education_status='MEZUN' AND deleted_at IS NULL)",Boolean.class,user));}
 public void request(UUID user,String email,String hash,Instant expiry){jdbc.update("INSERT INTO education_verifications(id,user_id,verification_type,school_email,code_hash,expires_at,university_department_id) SELECT ?,?,'SCHOOL_EMAIL',?,?,?,ud.id FROM user_profiles p LEFT JOIN university_departments ud ON ud.university_id=p.university_id AND ud.department_id=p.department_id AND ud.deleted_at IS NULL WHERE p.user_id=? ON CONFLICT(user_id,verification_type) WHERE deleted_at IS NULL DO UPDATE SET school_email=excluded.school_email,code_hash=excluded.code_hash,expires_at=excluded.expires_at,university_department_id=excluded.university_department_id,verified_at=NULL,review_status='PENDING',updated_at=CURRENT_TIMESTAMP,version=education_verifications.version+1",UUID.randomUUID(),user,email,hash,Timestamp.from(expiry),user);}
 public boolean confirm(UUID user,String hash){return jdbc.update("UPDATE education_verifications SET verified_at=CURRENT_TIMESTAMP,review_status='APPROVED',updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE user_id=? AND verification_type='SCHOOL_EMAIL' AND code_hash=? AND expires_at>CURRENT_TIMESTAMP AND verified_at IS NULL AND deleted_at IS NULL",user,hash)>0;}
 public void graduateRequest(UUID user,String evidence){jdbc.update("INSERT INTO education_verifications(id,user_id,verification_type,evidence,university_department_id) SELECT ?,?,'MANAGER_REVIEW',?,ud.id FROM user_profiles p LEFT JOIN university_departments ud ON ud.university_id=p.university_id AND ud.department_id=p.department_id AND ud.deleted_at IS NULL WHERE p.user_id=? ON CONFLICT(user_id,verification_type) WHERE deleted_at IS NULL DO UPDATE SET evidence=excluded.evidence,university_department_id=excluded.university_department_id,review_status='PENDING',review_reason=NULL,reviewed_by=NULL,reviewed_at=NULL,verified_at=NULL,updated_at=CURRENT_TIMESTAMP,version=education_verifications.version+1",UUID.randomUUID(),user,evidence.trim(),user);}
 public List<GraduateReviewResponse> reviews(int page,int size){return jdbc.query("SELECT ev.id,ev.user_id,concat(p.first_name,' ',p.last_name) applicant_name,ev.evidence,ev.review_status,ev.review_reason,ev.created_at,ev.version FROM education_verifications ev JOIN user_profiles p ON p.user_id=ev.user_id WHERE ev.verification_type='MANAGER_REVIEW' AND ev.deleted_at IS NULL ORDER BY CASE ev.review_status WHEN 'PENDING' THEN 0 ELSE 1 END,ev.created_at DESC LIMIT ? OFFSET ?",this::mapReview,size,page*size);}
 public long reviewCount(){return jdbc.queryForObject("SELECT count(*) FROM education_verifications WHERE verification_type='MANAGER_REVIEW' AND deleted_at IS NULL",Long.class);}
 @Transactional public boolean decide(UUID id,UUID manager,GraduateDecisionRequest request){boolean changed=jdbc.update("UPDATE education_verifications SET review_status=?,review_reason=?,reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP,verified_at=CASE WHEN ?='APPROVED' THEN CURRENT_TIMESTAMP ELSE NULL END,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=? AND verification_type='MANAGER_REVIEW' AND review_status='PENDING' AND version=? AND deleted_at IS NULL",request.status(),request.reason(),manager,request.status(),id,request.version())>0;if(changed)jdbc.update("INSERT INTO management_actions(id,actor_id,action,target_type,target_id,reason) VALUES (?,?,?,?,?,?)",UUID.randomUUID(),manager,request.status()+"_EDUCATION_VERIFICATION","EDUCATION_VERIFICATION",id,request.reason());return changed;}
 public GraduateReviewResponse review(UUID id){return jdbc.query("SELECT ev.id,ev.user_id,concat(p.first_name,' ',p.last_name) applicant_name,ev.evidence,ev.review_status,ev.review_reason,ev.created_at,ev.version FROM education_verifications ev JOIN user_profiles p ON p.user_id=ev.user_id WHERE ev.id=?",this::mapReview,id).stream().findFirst().orElse(null);}
 private GraduateReviewResponse mapReview(ResultSet r,int n)throws SQLException{return new GraduateReviewResponse(r.getObject("id",UUID.class),r.getObject("user_id",UUID.class),r.getString("applicant_name"),r.getString("evidence"),r.getString("review_status"),r.getString("review_reason"),r.getTimestamp("created_at").toInstant(),r.getLong("version"));}
 public EducationVerificationResponse get(UUID user){var rows=jdbc.query("SELECT verification_type,school_email,verified_at,expires_at FROM education_verifications WHERE user_id=? AND deleted_at IS NULL ORDER BY verified_at DESC NULLS LAST,created_at DESC LIMIT 1",(r,n)->new EducationVerificationResponse(r.getTimestamp("verified_at")!=null,r.getString("verification_type"),mask(r.getString("school_email")),instant(r.getTimestamp("verified_at")),instant(r.getTimestamp("expires_at"))),user);return rows.isEmpty()?new EducationVerificationResponse(false,null,null,null,null):rows.getFirst();}
 private Instant instant(Timestamp value){return value==null?null:value.toInstant();}private String mask(String email){if(email==null)return null;int at=email.indexOf('@');return email.substring(0,Math.min(2,at))+"***"+email.substring(at);}}
