package com.tanidikvar.api.retention.repository;
import com.tanidikvar.api.retention.dto.*;import java.sql.*;import java.time.Instant;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;
@Repository public class RetentionRepository {
 private final JdbcTemplate jdbc;public RetentionRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public boolean targetExists(String type,UUID id){String sql=switch(type){case "UNIVERSITY"->"SELECT EXISTS(SELECT 1 FROM universities WHERE id=? AND deleted_at IS NULL)";case "PROGRAM"->"SELECT EXISTS(SELECT 1 FROM programs WHERE id=? AND deleted_at IS NULL)";case "QUESTION"->"SELECT EXISTS(SELECT 1 FROM questions WHERE id=? AND deleted_at IS NULL)";case "TANIDIK"->"SELECT EXISTS(SELECT 1 FROM users WHERE id=? AND deleted_at IS NULL)";case "ANSWER"->"SELECT EXISTS(SELECT 1 FROM answers WHERE id=? AND deleted_at IS NULL AND moderated_at IS NULL)";default->null;};return sql!=null&&Boolean.TRUE.equals(jdbc.queryForObject(sql,Boolean.class,id));}
 public RetentionResponse set(String table,UUID user,String type,UUID target,boolean active){UUID id=UUID.randomUUID();return jdbc.query("INSERT INTO "+table+"(id,user_id,target_type,target_id,deleted_at) VALUES (?,?,?,?,CASE WHEN ? THEN NULL ELSE CURRENT_TIMESTAMP END) ON CONFLICT(user_id,target_type,target_id) DO UPDATE SET deleted_at=CASE WHEN ? THEN NULL ELSE CURRENT_TIMESTAMP END,updated_at=CURRENT_TIMESTAMP,version="+table+".version+1 RETURNING id,target_type,target_id,created_at,deleted_at,version",(r,n)->new RetentionResponse(r.getObject("id",UUID.class),r.getString("target_type"),r.getObject("target_id",UUID.class),r.getTimestamp("created_at").toInstant(),r.getTimestamp("deleted_at")==null,r.getLong("version")),id,user,type,target,active,active).getFirst();}
 public List<RetentionResponse> list(String table,UUID user,int page,int size){return jdbc.query("SELECT id,target_type,target_id,created_at,deleted_at,version FROM "+table+" WHERE user_id=? AND deleted_at IS NULL ORDER BY created_at DESC,id LIMIT ? OFFSET ?",(r,n)->new RetentionResponse(r.getObject("id",UUID.class),r.getString("target_type"),r.getObject("target_id",UUID.class),r.getTimestamp("created_at").toInstant(),true,r.getLong("version")),user,size,page*size);}
 public long count(String table,UUID user){return jdbc.queryForObject("SELECT count(*) FROM "+table+" WHERE user_id=? AND deleted_at IS NULL",Long.class,user);}
 public List<NotificationResponse> notifications(UUID user,int page,int size){return jdbc.query("SELECT * FROM notifications WHERE user_id=? AND deleted_at IS NULL ORDER BY created_at DESC,id LIMIT ? OFFSET ?",(r,n)->new NotificationResponse(r.getObject("id",UUID.class),r.getString("notification_type"),r.getString("title"),r.getString("body"),r.getString("target_type"),r.getObject("target_id",UUID.class),r.getTimestamp("created_at").toInstant(),instant(r.getTimestamp("read_at")),r.getLong("version")),user,size,page*size);}
 private Instant instant(Timestamp value){return value==null?null:value.toInstant();}
 public long notificationCount(UUID user){return jdbc.queryForObject("SELECT count(*) FROM notifications WHERE user_id=? AND deleted_at IS NULL",Long.class,user);}
 public boolean read(UUID user,UUID id){return jdbc.update("UPDATE notifications SET read_at=coalesce(read_at,CURRENT_TIMESTAMP),version=version+CASE WHEN read_at IS NULL THEN 1 ELSE 0 END WHERE id=? AND user_id=? AND deleted_at IS NULL",id,user)>0;}
 public NotificationPreferenceResponse preferences(UUID user){return jdbc.query("SELECT in_app_enabled,email_enabled,email_frequency,question_routing_enabled,version FROM notification_preferences WHERE user_id=? UNION ALL SELECT true,false,'DAILY',true,0 WHERE NOT EXISTS(SELECT 1 FROM notification_preferences WHERE user_id=?) LIMIT 1",(r,n)->new NotificationPreferenceResponse(r.getBoolean(1),r.getBoolean(2),r.getString(3),r.getBoolean(4),r.getLong(5)),user,user).getFirst();}
 public NotificationPreferenceResponse preferences(UUID user,NotificationPreferenceRequest request){return jdbc.query("INSERT INTO notification_preferences(user_id,in_app_enabled,email_enabled,email_frequency,question_routing_enabled,version) VALUES(?,?,?,?,?,0) ON CONFLICT(user_id) DO UPDATE SET in_app_enabled=excluded.in_app_enabled,email_enabled=excluded.email_enabled,email_frequency=excluded.email_frequency,question_routing_enabled=excluded.question_routing_enabled,updated_at=CURRENT_TIMESTAMP,version=notification_preferences.version+1 WHERE notification_preferences.version=? RETURNING in_app_enabled,email_enabled,email_frequency,question_routing_enabled,version",(r,n)->new NotificationPreferenceResponse(r.getBoolean(1),r.getBoolean(2),r.getString(3),r.getBoolean(4),r.getLong(5)),user,request.inAppEnabled(),request.emailEnabled(),request.emailFrequency(),request.questionRoutingEnabled(),request.version()).stream().findFirst().orElse(null);}
 private String title(long points){return points>=10000?"Efsane Tanıdık":points>=5000?"Usta Tanıdık":points>=2500?"Uzman Tanıdık":points>=1000?"Kıdemli Tanıdık":points>=500?"Deneyimli Tanıdık":points>=100?"Aktif Tanıdık":"Yeni Tanıdık";}
 public AnnualReportResponse report(UUID user,int year){return jdbc.queryForObject("WITH bounds AS (SELECT make_timestamptz(?,1,1,0,0,0,'UTC') start_at,make_timestamptz(?+1,1,1,0,0,0,'UTC') end_at), totals AS (SELECT user_id,sum(points) points FROM point_events,bounds WHERE created_at>=start_at AND created_at<end_at GROUP BY user_id), ranked AS (SELECT user_id,points,percent_rank() OVER(ORDER BY points) rank FROM totals) SELECT coalesce((SELECT points FROM totals WHERE user_id=?),0) points,(SELECT count(*) FROM point_events,bounds WHERE user_id=? AND created_at>=start_at AND created_at<end_at) events,(SELECT count(*) FROM answers,bounds WHERE author_id=? AND published_at>=start_at AND published_at<end_at AND deleted_at IS NULL) answers,(SELECT count(*) FROM questions q JOIN answers a ON a.id=q.best_answer_id,bounds WHERE a.author_id=? AND q.updated_at>=start_at AND q.updated_at<end_at) best,(SELECT count(*) FROM answer_likes l JOIN answers a ON a.id=l.answer_id,bounds WHERE a.author_id=? AND l.created_at>=start_at AND l.created_at<end_at AND l.deleted_at IS NULL) useful,(SELECT count(*) FROM evaluations,bounds WHERE author_id=? AND created_at>=start_at AND created_at<end_at AND deleted_at IS NULL) evaluations,(SELECT count(*) FROM structured_experiences,bounds WHERE author_id=? AND created_at>=start_at AND created_at<end_at AND deleted_at IS NULL) experiences,coalesce((SELECT rank*100 FROM ranked WHERE user_id=?),0) percentile",(r,n)->new AnnualReportResponse(year,r.getLong("points"),r.getLong("events"),r.getLong("answers"),r.getLong("best"),r.getLong("useful"),r.getLong("evaluations"),r.getLong("experiences"),r.getDouble("percentile")),year,year,user,user,user,user,user,user,user,user);}
 public GamificationResponse score(UUID user){var base=jdbc.query("SELECT ?::uuid user_id,coalesce(total_points,0) total_points,coalesce(event_count,0) event_count,last_event_at FROM user_point_totals WHERE user_id=? UNION ALL SELECT ?::uuid,0,0,NULL WHERE NOT EXISTS(SELECT 1 FROM user_point_totals WHERE user_id=?) LIMIT 1",(r,n)->new Object[]{r.getLong("total_points"),r.getLong("event_count"),instant(r.getTimestamp("last_event_at"))},user,user,user,user).getFirst();var badges=jdbc.query("SELECT title FROM user_achievements WHERE user_id=? ORDER BY featured DESC,awarded_at DESC LIMIT 3",(r,n)->r.getString(1),user);var expertise=jdbc.query("SELECT t.name,count(*) amount FROM answers a JOIN questions q ON q.id=a.question_id JOIN question_tags qt ON qt.question_id=q.id AND qt.deleted_at IS NULL JOIN tags t ON t.id=qt.tag_id AND t.deleted_at IS NULL WHERE a.author_id=? AND a.deleted_at IS NULL AND a.moderated_at IS NULL GROUP BY t.id,t.name HAVING count(*)>=3 ORDER BY amount DESC,t.name LIMIT 5",(r,n)->r.getString("name"),user);long points=(long)base[0];return new GamificationResponse(user,points,(long)base[1],title(points),badges,expertise,(Instant)base[2]);}
 public List<AchievementResponse> achievements(UUID user){return jdbc.query("SELECT * FROM user_achievements WHERE user_id=? ORDER BY featured DESC,awarded_at DESC",(r,n)->new AchievementResponse(r.getObject("id",UUID.class),r.getString("achievement_key"),r.getString("title"),(Integer)r.getObject("period_year"),r.getString("scope_type"),r.getObject("scope_id",UUID.class),r.getTimestamp("awarded_at").toInstant(),r.getBoolean("featured")),user);}
 public boolean showcase(UUID user,List<UUID> ids){jdbc.update("UPDATE user_achievements SET featured=false WHERE user_id=?",user);if(ids.isEmpty())return true;int updated=jdbc.update("UPDATE user_achievements SET featured=true WHERE user_id=? AND id IN ("+String.join(",",java.util.Collections.nCopies(ids.size(),"?"))+")",java.util.stream.Stream.concat(java.util.stream.Stream.of(user),ids.stream()).toArray());return updated==ids.size();}
 public List<LeaderboardEntryResponse> leaderboard(String period,UUID university,UUID department,int size){String filter=switch(period){case "DAILY"->" AND pe.created_at>=date_trunc('day',CURRENT_TIMESTAMP)";case "WEEKLY"->" AND pe.created_at>=date_trunc('week',CURRENT_TIMESTAMP)";case "MONTHLY"->" AND pe.created_at>=date_trunc('month',CURRENT_TIMESTAMP)";case "YEARLY"->" AND pe.created_at>=date_trunc('year',CURRENT_TIMESTAMP)";default->"";};return jdbc.query("SELECT pe.user_id,concat(up.first_name,' ',up.last_name) display_name,sum(pe.points) points,count(*) event_count,max(pe.created_at) last_event_at FROM point_events pe JOIN users u ON u.id=pe.user_id AND u.deleted_at IS NULL JOIN user_profiles up ON up.user_id=pe.user_id AND up.deleted_at IS NULL WHERE (?::uuid IS NULL OR up.university_id=?) AND (?::uuid IS NULL OR up.department_id=?)"+filter+" GROUP BY pe.user_id,up.first_name,up.last_name HAVING sum(pe.points)>0 ORDER BY points DESC,last_event_at DESC,pe.user_id LIMIT ?",(r,n)->{long points=r.getLong("points");List<String> badges=new ArrayList<>();if(points>=100)badges.add("İlk 100");if(points>=500)badges.add("Yardımsever");if(points>=1000)badges.add("Deneyim Elçisi");return new LeaderboardEntryResponse(r.getObject("user_id",UUID.class),r.getString("display_name"),points,r.getLong("event_count"),title(points),List.copyOf(badges),instant(r.getTimestamp("last_event_at")));},university,university,department,department,size);}
}
