package com.tanidikvar.api.poll.service;
import com.tanidikvar.api.common.dto.*;import com.tanidikvar.api.common.error.DomainException;import com.tanidikvar.api.poll.dto.*;import com.tanidikvar.api.poll.repository.PollRepository;import com.tanidikvar.api.profile.service.*;import java.time.Clock;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;
@Service public class PollService{
 private final PollRepository repository;private final InteractionPolicy interaction;private final ProfileSummaryService profiles;private final Clock clock;public PollService(PollRepository repository,InteractionPolicy interaction,ProfileSummaryService profiles,Clock clock){this.repository=repository;this.interaction=interaction;this.profiles=profiles;this.clock=clock;}
 private void context(UUID university,UUID program){if(!repository.context(university,program))throw new DomainException(404,"NOT_FOUND","Anket bağlamı bulunamadı.");}
 private PollResponse poll(UUID id){var poll=repository.find(id);if(poll==null)throw new DomainException(404,"NOT_FOUND","Anket bulunamadı.");return poll;}
 @Transactional public PollResponse create(UUID author,PollCreateRequest request){interaction.requireCompleted(author);if(!repository.verified(author))throw new DomainException(403,"TANIDIK_REQUIRED","Anket açmak için aktif Tanıdık doğrulaması gerekiyor.");if(!Objects.equals(request.universityId(),profiles.universityId(author)))throw new DomainException(403,"TANIDIK_UNIVERSITY_MISMATCH","Tanıdık olarak yalnız doğrulanmış üniversitende anket açabilirsin.");context(request.universityId(),request.programId());var labels=request.options().stream().map(v->v.strip().toLowerCase(Locale.ROOT)).toList();if(new HashSet<>(labels).size()!=labels.size())throw new DomainException(400,"DUPLICATE_OPTIONS","Anket seçenekleri farklı olmalı.");return poll(repository.create(author,request));}
 @Transactional(readOnly=true,isolation=Isolation.REPEATABLE_READ) public PageResponse<PollResponse> list(UUID university,UUID program,int page,int size){SearchQuery.page(page,size);context(university,program);var items=repository.ids(university,program,page,size).stream().map(this::poll).toList();return new PageResponse<>(items,page,size,repository.count(university,program));}
 @Transactional public PollResponse vote(UUID user,UUID id,PollVoteRequest request){interaction.requireCompleted(user);var poll=poll(id);if(poll.closesAt()!=null&&!poll.closesAt().isAfter(clock.instant()))throw new DomainException(409,"POLL_CLOSED","Anket kapanmış.");if(poll.verifiedOnly()&&!repository.verified(user))throw new DomainException(403,"VERIFICATION_REQUIRED","Bu ankete yalnız doğrulanmış Tanıdıklar katılabilir.");if(!repository.option(id,request.optionId()))throw new DomainException(400,"INVALID_OPTION","Anket seçeneğini kontrol et.");repository.vote(id,request.optionId(),user);return poll(id);}
}
