package com.tanidikvar.api.decision.service;import com.tanidikvar.api.common.dto.*;import com.tanidikvar.api.common.error.DomainException;import com.tanidikvar.api.decision.dto.*;import com.tanidikvar.api.decision.repository.DecisionContributionRepository;import java.math.BigDecimal;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class DecisionContributionService{private static final Set<String> METRICS=Set.of("WEEKLY_STUDY_HOURS","ATTENDANCE_LEVEL","PROJECT_INTENSITY","EXAM_INTENSITY","ENGLISH_PERCENT","GROUP_WORK_PERCENT","CAMPUS_HOURS","MONTHLY_HOUSING_COST","MONTHLY_TRANSPORT_COST","MONTHLY_FOOD_COST","JOB_SEARCH_MONTHS");private static final Set<String> TEMPLATES=Set.of("WHY_I_CHOSE","WISH_I_KNEW","EXPECTATION_REALITY","CHOOSE_AGAIN");private final DecisionContributionRepository repository;private final ContextContributorPolicy contributors;public DecisionContributionService(DecisionContributionRepository repository,ContextContributorPolicy contributors){this.repository=repository;this.contributors=contributors;}private void scope(UUID university,UUID program){if(!repository.university(university)||program!=null&&!repository.program(university,program))throw new DomainException(404,"NOT_FOUND","Karar bağlamı bulunamadı.");}
 @Transactional public void metric(UUID user,MetricContributionRequest request){scope(request.universityId(),request.programId());contributors.requireMatchingTanidik(user,request.universityId(),request.programId());if(!METRICS.contains(request.metricKey()))throw new DomainException(400,"INVALID_METRIC","Ölçüm türünü kontrol et.");if(Set.of("ENGLISH_PERCENT","GROUP_WORK_PERCENT","ATTENDANCE_LEVEL","PROJECT_INTENSITY","EXAM_INTENSITY").contains(request.metricKey())&&request.value().compareTo(BigDecimal.valueOf(100))>0)throw new DomainException(400,"INVALID_VALUE","Ölçüm değerini kontrol et.");repository.metric(user,request);}
 @Transactional(readOnly=true) public List<MetricSummaryResponse> metrics(UUID university,UUID program){scope(university,program);return repository.metrics(university,program);}
 @Transactional public ExperienceResponse experience(UUID user,ExperienceRequest request){scope(request.universityId(),request.programId());contributors.requireMatchingTanidik(user,request.universityId(),request.programId());if(!TEMPLATES.contains(request.templateType()))throw new DomainException(400,"INVALID_TEMPLATE","Deneyim şablonunu kontrol et.");String sentiment=request.sentiment()==null?"NEUTRAL":request.sentiment().toUpperCase(Locale.ROOT);if(!Set.of("POSITIVE","NEGATIVE","NEUTRAL").contains(sentiment))throw new DomainException(400,"INVALID_SENTIMENT","Görüş türünü kontrol et.");return repository.experience(user,request,sentiment);}
 @Transactional(readOnly=true) public PageResponse<ExperienceResponse> experiences(UUID university,UUID program,int page,int size){scope(university,program);SearchQuery.page(page,size);return new PageResponse<>(repository.experiences(university,program,page,size),page,size,repository.experienceCount(university,program));}
 @Transactional public void career(UUID user,GraduateOutcomeRequest request){scope(request.universityId(),request.programId());contributors.requireMatchingTanidik(user,request.universityId(),request.programId());if(!repository.graduate(user))throw new DomainException(403,"GRADUATE_REQUIRED","Kariyer katkısı yalnız mezun profiliyle paylaşılabilir.");repository.career(user,request);}
 @Transactional(readOnly=true) public CareerSummaryResponse career(UUID university,UUID program){scope(university,program);return repository.careerSummary(university,program);}
 @Transactional(readOnly=true) public SentimentSummaryResponse sentiments(UUID university,UUID program){scope(university,program);return repository.sentiments(university,program);}
}
