package com.tanidikvar.api.profile.controller;
import com.tanidikvar.api.answer.dto.AdminAnswerResponse;import com.tanidikvar.api.answer.service.AdminAnswerService;import com.tanidikvar.api.common.dto.PageResponse;import com.tanidikvar.api.profile.dto.*;import com.tanidikvar.api.profile.service.PublicAdminProfileService;import java.util.UUID;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/tanidiklar") public class PublicTanidikProfileController{
 private final PublicAdminProfileService profiles;private final AdminAnswerService answers;public PublicTanidikProfileController(PublicAdminProfileService profiles,AdminAnswerService answers){this.profiles=profiles;this.answers=answers;}
 @GetMapping public PageResponse<PublicTanidikProfileResponse> search(@RequestParam(required=false) String q,@RequestParam(required=false) UUID universityId,@RequestParam(required=false) UUID departmentId,@RequestParam(required=false) String educationStatus,@RequestParam(required=false) Integer classYear,@RequestParam(required=false) Boolean verified,@RequestParam(required=false) String expertise,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){var result=profiles.search(q,true,universityId,departmentId,educationStatus,classYear,verified,expertise,page,size);return new PageResponse<>(result.items().stream().map(this::map).toList(),result.page(),result.size(),result.totalElements());}
 @GetMapping("/{id}") public PublicTanidikProfileResponse get(@PathVariable UUID id){return map(profiles.get(id));}
 @GetMapping("/{id}/answers") public PageResponse<AdminAnswerResponse> answers(@PathVariable UUID id,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){profiles.get(id);return answers.history(id,page,size);}
 private PublicTanidikProfileResponse map(PublicAdminProfileResponse p){return new PublicTanidikProfileResponse(p.id(),p.name(),p.activeAdmin(),p.educationVerified(),p.universityName(),p.departmentName(),p.educationStatus(),p.classYear(),p.graduationYear(),p.biography(),p.occupation(),p.company(),p.linkedinUrl(),p.portfolioUrl(),p.avatarFileId(),p.answerCount(),p.communityAnswerCount(),p.helpfulVoteCount(),p.bestAnswerCount(),p.helpedPeopleCount(),p.createdAt());}
}
