package com.tanidikvar.api.retention.service;
import com.tanidikvar.api.common.dto.*;import com.tanidikvar.api.common.error.DomainException;import com.tanidikvar.api.retention.dto.*;import com.tanidikvar.api.retention.repository.RetentionRepository;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class RetentionService {
 private final RetentionRepository repository;public RetentionService(RetentionRepository repository){this.repository=repository;}
 @Transactional public RetentionResponse follow(UUID user,RetentionRequest request){if(!request.targetType().equals("UNIVERSITY"))throw invalid();target(request);return repository.set("follows",user,request.targetType(),request.targetId(),request.active());}
 @Transactional public RetentionResponse save(UUID user,RetentionRequest request){if(request.targetType().equals("TANIDIK"))throw invalid();target(request);return repository.set("saved_items",user,request.targetType(),request.targetId(),request.active());}
 @Transactional(readOnly=true) public PageResponse<RetentionResponse> follows(UUID user,int page,int size){SearchQuery.page(page,size);return new PageResponse<>(repository.list("follows",user,page,size),page,size,repository.count("follows",user));}
 @Transactional(readOnly=true) public PageResponse<RetentionResponse> saved(UUID user,int page,int size){SearchQuery.page(page,size);return new PageResponse<>(repository.list("saved_items",user,page,size),page,size,repository.count("saved_items",user));}
 @Transactional(readOnly=true) public PageResponse<NotificationResponse> notifications(UUID user,int page,int size){SearchQuery.page(page,size);return new PageResponse<>(repository.notifications(user,page,size),page,size,repository.notificationCount(user));}
 @Transactional public void read(UUID user,UUID id){if(!repository.read(user,id))throw new DomainException(404,"NOT_FOUND","Bildirim bulunamadı.");}
 @Transactional(readOnly=true) public NotificationPreferenceResponse preferences(UUID user){return repository.preferences(user);}
 @Transactional public NotificationPreferenceResponse preferences(UUID user,NotificationPreferenceRequest request){var result=repository.preferences(user,request);if(result==null)throw new DomainException(409,"STALE_VERSION","Bildirim tercihleri değişmiş. Güncel ayarları yükle.");return result;}
 @Transactional(readOnly=true) public GamificationResponse score(UUID user){return repository.score(user);}
 @Transactional(readOnly=true) public List<AchievementResponse> achievements(UUID user){return repository.achievements(user);}
 @Transactional public List<AchievementResponse> showcase(UUID user,AchievementShowcaseRequest request){if(request.achievementIds()==null||new HashSet<>(request.achievementIds()).size()!=request.achievementIds().size())throw new DomainException(400,"INVALID_ACHIEVEMENTS","Rozet seçimini kontrol et.");if(!repository.showcase(user,request.achievementIds()))throw new DomainException(404,"NOT_FOUND","Rozet bulunamadı.");return repository.achievements(user);}
 @Transactional(readOnly=true) public AnnualReportResponse report(UUID user,int year){int selected=year==0?java.time.Year.now().getValue():year;if(selected<2020||selected>java.time.Year.now().getValue())throw new DomainException(400,"INVALID_YEAR","Karne yılını kontrol et.");return repository.report(user,selected);}
 @Transactional(readOnly=true) public List<LeaderboardEntryResponse> leaderboard(String period,UUID university,UUID department,int size){if(!Set.of("ALL_TIME","DAILY","WEEKLY","MONTHLY","YEARLY").contains(period)||size<1||size>100)throw new DomainException(400,"INVALID_QUERY","Sıralama filtresini kontrol et.");return repository.leaderboard(period,university,department,size);}
 private DomainException invalid(){return new DomainException(400,"INVALID_TARGET","Hedef türünü kontrol et.");}
 private void target(RetentionRequest request){if(!repository.targetExists(request.targetType(),request.targetId()))throw new DomainException(404,"NOT_FOUND","Takip veya kayıt hedefi bulunamadı.");}
}
