INSERT INTO question_templates(id,category,title,body,scope_hint) VALUES
(md5('template-expanded-1')::uuid,'EĞİTİM','Derslerde teori ve uygulama dengesi nasıl?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-2')::uuid,'EĞİTİM','Seçmeli ders çeşitliliği yeterli mi?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-3')::uuid,'EĞİTİM','Laboratuvar ve atölyeler ne kadar kullanılıyor?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-4')::uuid,'EĞİTİM','Ders programı çalışmaya uygun mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-5')::uuid,'EĞİTİM','Sınavların zorluk seviyesi nasıl?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-6')::uuid,'EĞİTİM','Proje ve ödev yükü dönem içinde nasıl dağılıyor?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-7')::uuid,'EĞİTİM','Akademik danışmanlık gerçekten işliyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-8')::uuid,'EĞİTİM','Çift anadal ve yandal yapmak ne kadar mümkün?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-9')::uuid,'EĞİTİM','Ders kayıt döneminde hangi sorunlar yaşanıyor?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-10')::uuid,'EĞİTİM','Mezun olmak için en zorlayıcı dersler hangileri?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-11')::uuid,'KAMPÜS','Kampüste bir gün genellikle nasıl geçiyor?',NULL,'UNIVERSITY'),
(md5('template-expanded-12')::uuid,'KAMPÜS','Kütüphane çalışma koşulları yeterli mi?',NULL,'UNIVERSITY'),
(md5('template-expanded-13')::uuid,'KAMPÜS','Kampüs güvenliği gece saatlerinde nasıl?',NULL,'UNIVERSITY'),
(md5('template-expanded-14')::uuid,'KAMPÜS','Spor tesislerinden yararlanmak kolay mı?',NULL,'UNIVERSITY'),
(md5('template-expanded-15')::uuid,'KAMPÜS','Öğrenci kulüpleri ne kadar aktif?',NULL,'UNIVERSITY'),
(md5('template-expanded-16')::uuid,'KAMPÜS','Kampüste sessiz çalışma alanı bulunuyor mu?',NULL,'UNIVERSITY'),
(md5('template-expanded-17')::uuid,'KAMPÜS','Kampüs içi ulaşım pratik mi?',NULL,'UNIVERSITY'),
(md5('template-expanded-18')::uuid,'KAMPÜS','Yemekhane yoğunluğu ve kalitesi nasıl?',NULL,'UNIVERSITY'),
(md5('template-expanded-19')::uuid,'KAMPÜS','Kampüs çevresinde öğrenciler nerede vakit geçiriyor?',NULL,'UNIVERSITY'),
(md5('template-expanded-20')::uuid,'KAMPÜS','Engelli öğrenciler için erişilebilirlik yeterli mi?',NULL,'UNIVERSITY'),
(md5('template-expanded-21')::uuid,'KARİYER','Staj bulurken okulun desteği oluyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-22')::uuid,'KARİYER','Mezunlar ilk işlerini ne kadar sürede buluyor?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-23')::uuid,'KARİYER','Kariyer merkezi gerçekten fayda sağlıyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-24')::uuid,'KARİYER','Sektör etkinlikleri ve şirket buluşmaları sık mı?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-25')::uuid,'KARİYER','Bu program hangi mesleklere hazırlıyor?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-26')::uuid,'KARİYER','Mezun ağı iş bulmaya yardımcı oluyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-27')::uuid,'KARİYER','Okurken yarı zamanlı çalışmak mümkün mü?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-28')::uuid,'KARİYER','Portföy geliştirmek için hangi fırsatlar var?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-29')::uuid,'KARİYER','Yurt dışı kariyer hedefi için eğitim yeterli mi?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-30')::uuid,'KARİYER','Yeni mezun maaş ve rol beklentileri nasıl?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-31')::uuid,'HAZIRLIK','Hazırlık eğitiminin seviyesi nasıl?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-32')::uuid,'HAZIRLIK','Muafiyet sınavına nasıl hazırlanmak gerekir?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-33')::uuid,'HAZIRLIK','Hazırlıkta devam zorunluluğu uygulanıyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-34')::uuid,'HAZIRLIK','Hazırlık bir yılda rahatça tamamlanabilir mi?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-35')::uuid,'HAZIRLIK','Dil becerileri bölüm derslerine yetiyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-36')::uuid,'HAZIRLIK','Kur sistemi ve sınıf geçme koşulları nasıl?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-37')::uuid,'HAZIRLIK','Hazırlıkta kullanılan kaynaklar yeterli mi?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-38')::uuid,'HAZIRLIK','Konuşma pratiği için imkân sunuluyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-39')::uuid,'HAZIRLIK','İsteğe bağlı hazırlık okumaya değer mi?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-40')::uuid,'HAZIRLIK','Hazırlık kampüsü ana kampüsten farklı mı?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-41')::uuid,'ERASMUS','Erasmus kontenjanları yeterli mi?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-42')::uuid,'ERASMUS','Hangi ülkelerle aktif anlaşmalar var?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-43')::uuid,'ERASMUS','Ders eşleştirmede sorun yaşanıyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-44')::uuid,'ERASMUS','Erasmus hibesi giderleri karşılıyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-45')::uuid,'ERASMUS','Başvuru süreci ne kadar zor?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-46')::uuid,'ERASMUS','Dil sınavına nasıl hazırlanmak gerekir?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-47')::uuid,'ERASMUS','Dönüşte dönem uzatma riski var mı?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-48')::uuid,'ERASMUS','Staj hareketliliğinden yararlanan var mı?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-49')::uuid,'ERASMUS','Değişim öğrencilerine danışmanlık yeterli mi?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-50')::uuid,'ERASMUS','Erasmus için en uygun sınıf hangisi?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-51')::uuid,'YURT','Yakındaki devlet yurtlarının koşulları nasıl?',NULL,'UNIVERSITY'),
(md5('template-expanded-52')::uuid,'YURT','Özel yurt fiyatları ve imkânları nasıl?',NULL,'UNIVERSITY'),
(md5('template-expanded-53')::uuid,'YURT','Eve çıkmak için hangi semtler tercih ediliyor?',NULL,'UNIVERSITY'),
(md5('template-expanded-54')::uuid,'YURT','Yurttan kampüse ulaşım ne kadar sürüyor?',NULL,'UNIVERSITY'),
(md5('template-expanded-55')::uuid,'YURT','Yurt başvurusunda nelere dikkat edilmeli?',NULL,'UNIVERSITY'),
(md5('template-expanded-56')::uuid,'YURT','Ev arkadaşı bulmak için güvenli yollar neler?',NULL,'UNIVERSITY'),
(md5('template-expanded-57')::uuid,'YURT','Barınma maliyeti dönem içinde nasıl değişiyor?',NULL,'UNIVERSITY'),
(md5('template-expanded-58')::uuid,'YURT','Yurtlarda internet ve çalışma ortamı yeterli mi?',NULL,'UNIVERSITY'),
(md5('template-expanded-59')::uuid,'YURT','Hazırlık öğrencileri nerede kalmayı tercih ediyor?',NULL,'UNIVERSITY'),
(md5('template-expanded-60')::uuid,'YURT','Deprem güvenliği açısından barınma seçenekleri nasıl?',NULL,'UNIVERSITY'),
(md5('template-expanded-61')::uuid,'SOSYAL HAYAT','Öğrenciler hafta sonu neler yapıyor?',NULL,'UNIVERSITY'),
(md5('template-expanded-62')::uuid,'SOSYAL HAYAT','Kulüplere katılmak arkadaş edinmeyi kolaylaştırıyor mu?',NULL,'UNIVERSITY'),
(md5('template-expanded-63')::uuid,'SOSYAL HAYAT','Şehirde öğrenci bütçesine uygun etkinlikler var mı?',NULL,'UNIVERSITY'),
(md5('template-expanded-64')::uuid,'SOSYAL HAYAT','Kampüs festivalleri ve etkinlikleri nasıl?',NULL,'UNIVERSITY'),
(md5('template-expanded-65')::uuid,'SOSYAL HAYAT','Yeni başlayan biri çevre edinmekte zorlanır mı?',NULL,'UNIVERSITY'),
(md5('template-expanded-66')::uuid,'SOSYAL HAYAT','Bölüm öğrencileri birlikte etkinlik düzenliyor mu?',NULL,'UNIVERSITY'),
(md5('template-expanded-67')::uuid,'SOSYAL HAYAT','Sanat ve kültür etkinliklerine erişim kolay mı?',NULL,'UNIVERSITY'),
(md5('template-expanded-68')::uuid,'SOSYAL HAYAT','Gece ulaşımı sosyal hayatı kısıtlıyor mu?',NULL,'UNIVERSITY'),
(md5('template-expanded-69')::uuid,'SOSYAL HAYAT','Üniversiteler arası etkinlikler yaygın mı?',NULL,'UNIVERSITY'),
(md5('template-expanded-70')::uuid,'SOSYAL HAYAT','Sosyal hayat ile dersleri dengelemek mümkün mü?',NULL,'UNIVERSITY'),
(md5('template-expanded-71')::uuid,'MALİYET','Bir öğrencinin aylık gerçek gideri ne kadar?',NULL,'UNIVERSITY'),
(md5('template-expanded-72')::uuid,'MALİYET','Yemekhane ve dışarıda yemek fiyatları nasıl?',NULL,'UNIVERSITY'),
(md5('template-expanded-73')::uuid,'MALİYET','Aylık ulaşım bütçesi ne kadar oluyor?',NULL,'UNIVERSITY'),
(md5('template-expanded-74')::uuid,'MALİYET','Kampüs çevresinde kiralar hangi aralıkta?',NULL,'UNIVERSITY'),
(md5('template-expanded-75')::uuid,'MALİYET','Ders materyalleri ek maliyet çıkarıyor mu?',NULL,'UNIVERSITY'),
(md5('template-expanded-76')::uuid,'MALİYET','Burs ve yarı zamanlı iş imkânları yeterli mi?',NULL,'UNIVERSITY'),
(md5('template-expanded-77')::uuid,'MALİYET','Kahve ve sosyal etkinlik bütçesi ne kadar?',NULL,'UNIVERSITY'),
(md5('template-expanded-78')::uuid,'MALİYET','Şehirde öğrenci indirimi yaygın mı?',NULL,'UNIVERSITY'),
(md5('template-expanded-79')::uuid,'MALİYET','İlk kayıt döneminde hangi masraflar çıkıyor?',NULL,'UNIVERSITY'),
(md5('template-expanded-80')::uuid,'MALİYET','Maliyetleri azaltmak için öğrenciler ne yapıyor?',NULL,'UNIVERSITY'),
(md5('template-expanded-81')::uuid,'HOCALAR','Hocalara ders dışında ulaşmak kolay mı?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-82')::uuid,'HOCALAR','Hocaların anlatım kalitesi genel olarak nasıl?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-83')::uuid,'HOCALAR','Notlandırma şeffaf ve adil mi?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-84')::uuid,'HOCALAR','Araştırma projelerine öğrenci kabul ediliyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-85')::uuid,'HOCALAR','Akademik kadro sektörle bağlantılı mı?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-86')::uuid,'HOCALAR','Ofis saatleri düzenli uygulanıyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-87')::uuid,'HOCALAR','Öğrenci geri bildirimi dikkate alınıyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-88')::uuid,'HOCALAR','Referans mektubu almak kolay mı?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-89')::uuid,'HOCALAR','Danışman hocalar öğrenciyi yönlendiriyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-90')::uuid,'HOCALAR','Hocalar proje ve yarışmaları destekliyor mu?',NULL,'UNIVERSITY_DEPARTMENT'),
(md5('template-expanded-91')::uuid,'YENİ KAZANAN','Kayıt haftasında hangi işlemleri önce yapmalıyım?',NULL,'UNIVERSITY'),
(md5('template-expanded-92')::uuid,'YENİ KAZANAN','İlk gün kampüste nereye gitmeliyim?',NULL,'UNIVERSITY'),
(md5('template-expanded-93')::uuid,'YENİ KAZANAN','İlk yüz günde mutlaka yapılması gerekenler neler?',NULL,'UNIVERSITY'),
(md5('template-expanded-94')::uuid,'YENİ KAZANAN','Ders kayıt ekranında nelere dikkat etmeliyim?',NULL,'UNIVERSITY'),
(md5('template-expanded-95')::uuid,'YENİ KAZANAN','Öğrenci kartı ve ulaşım kartı nasıl alınır?',NULL,'UNIVERSITY'),
(md5('template-expanded-96')::uuid,'YENİ KAZANAN','Hangi kulüpler yeni öğrencilere uygun?',NULL,'UNIVERSITY'),
(md5('template-expanded-97')::uuid,'YENİ KAZANAN','Kampüse gelirken yanımda ne getirmeliyim?',NULL,'UNIVERSITY'),
(md5('template-expanded-98')::uuid,'YENİ KAZANAN','Hazırlık ve bölüm oryantasyonu faydalı mı?',NULL,'UNIVERSITY'),
(md5('template-expanded-99')::uuid,'YENİ KAZANAN','Güvenilir ev arkadaşı nasıl bulunur?',NULL,'UNIVERSITY'),
(md5('template-expanded-100')::uuid,'YENİ KAZANAN','Yeni şehirde uyum sürecini ne kolaylaştırır?',NULL,'UNIVERSITY');

