package com.tanidikvar.api.poll.repository;
import com.tanidikvar.api.poll.dto.*;import java.sql.*;import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;
@Repository public class PollRepository{
 private final JdbcTemplate jdbc;public PollRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public boolean context(UUID university,UUID program){return program==null?Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM universities WHERE id=? AND deleted_at IS NULL)",Boolean.class,university)):Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM university_departments WHERE id=? AND university_id=? AND deleted_at IS NULL)",Boolean.class,program,university));}
 public boolean verified(UUID user){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM users u JOIN admin_applications a ON a.id=u.active_verification_application_id AND a.applicant_id=u.id AND a.status='APPROVED' AND a.deleted_at IS NULL WHERE u.id=? AND u.authority='TANIDIK' AND u.deleted_at IS NULL)",Boolean.class,user));}
 public UUID create(UUID author,PollCreateRequest request){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO polls(id,author_id,university_id,university_department_id,question,verified_only,closes_at) VALUES (?,?,?,?,?,?,?)",id,author,request.universityId(),request.programId(),request.question().strip(),request.verifiedOnly(),request.closesAt()==null?null:Timestamp.from(request.closesAt()));for(int i=0;i<request.options().size();i++)jdbc.update("INSERT INTO poll_options(id,poll_id,label,position) VALUES (?,?,?,?)",UUID.randomUUID(),id,request.options().get(i).strip(),i);return id;}
 public PollResponse find(UUID id){return jdbc.query("SELECT p.*,concat_ws(' ',up.first_name,up.last_name) author_name FROM polls p JOIN user_profiles up ON up.user_id=p.author_id AND up.deleted_at IS NULL WHERE p.id=? AND p.deleted_at IS NULL",(r,n)->map(r),id).stream().findFirst().orElse(null);}
 private PollResponse map(ResultSet r)throws SQLException{UUID id=r.getObject("id",UUID.class);var options=jdbc.query("SELECT o.id,o.label,o.position,count(v.id) votes FROM poll_options o LEFT JOIN poll_votes v ON v.option_id=o.id AND v.deleted_at IS NULL WHERE o.poll_id=? AND o.deleted_at IS NULL GROUP BY o.id ORDER BY o.position",(x,n)->new PollOptionResponse(x.getObject("id",UUID.class),x.getString("label"),x.getInt("position"),x.getLong("votes")),id);long verifiedVotes=jdbc.queryForObject("SELECT count(*) FROM poll_votes v WHERE v.poll_id=? AND v.deleted_at IS NULL AND (EXISTS(SELECT 1 FROM education_verifications ev WHERE ev.user_id=v.voter_id AND ev.verified_at IS NOT NULL AND ev.deleted_at IS NULL) OR EXISTS(SELECT 1 FROM users u JOIN admin_applications a ON a.id=u.active_verification_application_id AND a.status='APPROVED' AND a.deleted_at IS NULL WHERE u.id=v.voter_id AND u.authority='TANIDIK' AND u.deleted_at IS NULL))",Long.class,id);return new PollResponse(id,r.getObject("author_id",UUID.class),r.getString("author_name"),r.getObject("university_id",UUID.class),r.getObject("university_department_id",UUID.class),r.getString("question"),r.getBoolean("verified_only"),instant(r.getTimestamp("closes_at")),r.getTimestamp("created_at").toInstant(),options,options.stream().mapToLong(PollOptionResponse::voteCount).sum(),verifiedVotes);}
 private Instant instant(Timestamp value){return value==null?null:value.toInstant();}
 public List<UUID> ids(UUID university,UUID program,int page,int size){return jdbc.queryForList("SELECT id FROM polls WHERE university_id=? AND university_department_id IS NOT DISTINCT FROM ? AND deleted_at IS NULL ORDER BY created_at DESC,id LIMIT ? OFFSET ?",UUID.class,university,program,size,page*size);}
 public long count(UUID university,UUID program){return jdbc.queryForObject("SELECT count(*) FROM polls WHERE university_id=? AND university_department_id IS NOT DISTINCT FROM ? AND deleted_at IS NULL",Long.class,university,program);}
 public boolean option(UUID poll,UUID option){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM poll_options WHERE id=? AND poll_id=? AND deleted_at IS NULL)",Boolean.class,option,poll));}
 public void vote(UUID poll,UUID option,UUID user){jdbc.update("INSERT INTO poll_votes(id,poll_id,option_id,voter_id) VALUES (?,?,?,?) ON CONFLICT(poll_id,voter_id) DO UPDATE SET option_id=excluded.option_id,deleted_at=NULL,updated_at=CURRENT_TIMESTAMP,version=poll_votes.version+1",UUID.randomUUID(),poll,option,user);}
}
