package com.tanidikvar.api.report.repository;
import com.tanidikvar.api.report.dto.QuestionReportResponse;import java.sql.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;
@Repository public class QuestionReportRepository{
 private final JdbcTemplate jdbc;public QuestionReportRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 private QuestionReportResponse map(ResultSet r,int n)throws SQLException{return new QuestionReportResponse(r.getObject("id",UUID.class),r.getObject("question_id",UUID.class),r.getString("question_title"),r.getObject("question_author_id",UUID.class),r.getString("question_author_name"),r.getObject("reporter_id",UUID.class),r.getString("reporter_name"),r.getString("reason"),r.getString("status"),r.getTimestamp("created_at").toInstant(),r.getObject("reviewed_by",UUID.class),r.getTimestamp("reviewed_at")==null?null:r.getTimestamp("reviewed_at").toInstant(),r.getString("resolution_reason"),r.getLong("version"));}
 private static final String SELECT="SELECT r.*,q.title question_title,q.author_id question_author_id,coalesce(nullif(concat_ws(' ',qap.first_name,qap.last_name),''),qa.email) question_author_name,coalesce(nullif(concat_ws(' ',p.first_name,p.last_name),''),u.email) reporter_name FROM question_reports r JOIN questions q ON q.id=r.question_id JOIN users qa ON qa.id=q.author_id LEFT JOIN user_profiles qap ON qap.user_id=qa.id AND qap.deleted_at IS NULL JOIN users u ON u.id=r.reporter_id LEFT JOIN user_profiles p ON p.user_id=u.id AND p.deleted_at IS NULL WHERE r.deleted_at IS NULL ";
 public void create(UUID id,UUID question,UUID reporter,String reason){jdbc.update("INSERT INTO question_reports(id,question_id,reporter_id,reason) VALUES (?,?,?,?)",id,question,reporter,reason);}
 public Optional<QuestionReportResponse> find(UUID id){return jdbc.query(SELECT+"AND r.id=?",this::map,id).stream().findFirst();}
 public List<QuestionReportResponse> list(String q,String status,String sort,int page,int size){String order=switch(sort){case "OLDEST"->"r.created_at,r.id";case "STATUS"->"r.status,r.created_at DESC,r.id";default->"r.created_at DESC,r.id";};return jdbc.query(SELECT+"AND position(search_fold(?) in search_fold(concat_ws(' ',q.title,r.reason,p.first_name,p.last_name,u.email)))>0 AND (?='' OR r.status=?) ORDER BY "+order+" LIMIT ? OFFSET ?",this::map,q,status,status,size,page*size);}
 public long count(String q,String status){return jdbc.queryForObject("SELECT count(*) FROM question_reports r JOIN questions qu ON qu.id=r.question_id JOIN users u ON u.id=r.reporter_id LEFT JOIN user_profiles p ON p.user_id=u.id AND p.deleted_at IS NULL WHERE r.deleted_at IS NULL AND position(search_fold(?) in search_fold(concat_ws(' ',qu.title,r.reason,p.first_name,p.last_name,u.email)))>0 AND (?='' OR r.status=?)",Long.class,q,status,status);}
 public void decide(UUID id,UUID actor,String status,String reason){jdbc.update("UPDATE question_reports SET status=?,reviewed_by=?,reviewed_at=clock_timestamp(),resolution_reason=?,updated_at=clock_timestamp(),version=version+1 WHERE id=?",status,actor,reason,id);}
}
